name: player
description: Creative Podcast Player.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  podcast_search: ^0.5.0
  provider: ^6.0.1
  url_launcher: ^6.0.15
  audioplayers: ^0.20.1
  timeago: ^3.1.0
  flutter_markdown: ^0.6.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.5

flutter:
  uses-material-design: true
